# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates verbose markdown optimized for Claude Code.
    # Includes a behavioral rules section and full detail.
    class ClaudeSerializer < MarkdownSerializer
      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives Claude Code deep context about this Rails application's
          structure, patterns, and conventions. Use it to write idiomatic code
          that matches this project's style.
        MD
      end

      def footer
        rules = []
        rules << "## Behavioral Rules"
        rules << ""
        rules << "When working in this codebase:"
        rules << "- Follow existing patterns and conventions detected above"
        rules << "- Use the database schema as the source of truth for column names and types"
        rules << "- Respect existing associations and validations when modifying models"
        rules << "- Match the project's architecture style (#{architecture_summary})" if architecture_summary
        rules << "- Run `bundle exec rspec` after making changes to verify correctness"
        rules << ""
        rules << super
        rules.join("\n")
      end

      def architecture_summary
        arch = context.dig(:conventions, :architecture)
        arch&.any? ? arch.join(", ") : nil
      end
    end
  end
end
