# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates GitHub Flavored Markdown with task-oriented sections
    # optimized for GitHub Copilot instructions format.
    class CopilotSerializer < MarkdownSerializer
      private

      def header
        <<~MD
          # #{context[:app_name]} — Copilot Instructions

          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}

          Use this context to generate code that fits this project's structure and patterns.
        MD
      end

      def footer
        <<~MD
          ---
          _Auto-generated. Run `rails ai:context` to regenerate._
        MD
      end
    end
  end
end
