# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates compact, imperative-tone rules for Cursor and Windsurf.
    # Focuses on actionable directives rather than verbose documentation.
    class RulesSerializer < MarkdownSerializer
      private

      def header
        <<~MD
          # #{context[:app_name]} — Project Rules

          Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
        MD
      end

      def footer
        <<~MD
          ---
          _Auto-generated by rails-ai-context. Run `rails ai:context` to regenerate._
        MD
      end
    end
  end
end
